### ISSUE TITLE
Regression in Undo 

### ISSUE THREAD

**Issue by abn5x** [FocalPaint/FocalPaint#12]
Same issue as described here:

https://github.com/FocalPaint/FocalPaint/issues/8#issue-756573410

**Comment by briend** [comment]
I think this is finally fixed. I ended up just popping up the progress dialog and prevent painting during the autosave.   It will still wait 3 seconds after your last stroke before it trigger, but you can no longer paint during any kind of saving activity, which is just much simpler even if it is a bit annoying.  Saving and loading is actually quite a bit faster since I increased the chunk size with the compression method.
