### ISSUE TITLE
Undo?

### ISSUE THREAD

**Issue by sobotka** [FocalPaint/FocalPaint#2]
Where the hell is undo?

**Comment by briend** [comment]
“We don't make mistakes, just happy little accidents.” 
― Bob Ross

I have some ideas on how to implement this, at least for strokes

https://developer.apple.com/documentation/foundation/undomanager

Thinking something like this:

1. Active Layer selected: Copy Entire Active Layer to tempLayer
2. Stroke Begins: Begin accumulating dirty rects into one larger dirty rect  (CGRect.union)
3. Stroke Ends: Copy the directyRect region from tempLayer into the UndoStack, along with metadata: layerID, textureOrigin

As long as I can copy a whole layer in-between strokeEnd and the next strokeBegin, I think this would work pretty well.
To Undo would just be a matter of blitting the rect into the layer as you pop items off the undo stack.  Probably want Redo as well so it's more like traversing the stack.  And I guess once you start new strokes it would invalidate any newer Undo items.

**Comment by briend** [comment]
Latest v1.30 beta now has two-finger tap-to-undo and three-finger tap-to-redo.  Only 10 levels at for now due to the pretty hefty memory requirements.  A single stroke could potentially create a dirty rect the size of the entire layer, which is ~185MB.  I did manage to react to iOS memory "warnings" and automatically flush the undo stack and save the doc.  Better than crashing!
