### ISSUE TITLE
Two finger drag flakey

### ISSUE THREAD

**Issue by sobotka** [FocalPaint/FocalPaint#3]
Initiates with two finger, but extremely challenging to move as it drops out. Appears to be getting stuck 1/3rd of the screen down.

**Comment by briend** [comment]
This should be fixed in 1.22 uploading to TestFlight now.  My logic to prevent dragging the window off the screen entirely was very flawed.  It still is a bit flawed, but I have added a "reset and center" button which was missing anyway, and will recover the window if you somehow manage to drag it off the screen.
